# -*- coding: utf-8 -*-
"""Análise de Algoritmo .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uyxM7lWXhkSKPDtDhuDeZdkJM8JYY_w
"""

# Importar os módulos do sistema operacional
import os
import locale

# Reiniciar o processo Python
os.kill(os.getpid(), 9)

# Definições e funções para todos os exemplos
# encoding: iso-8859-1

from datetime import datetime
import random

# Ajustando a localização para o Brasil
import os
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR')
from datetime import datetime
import pytz

# Define o fuso horário para o Brasil (Brasília)
con_fuso_horario = pytz.timezone("America/Sao_Paulo")

conSeparador= "\nXXXXXXXXXXXXX---XXXXXXXXXXXXX\n"

# Função formatar tempo de execução (dado tempo de inicio e fim, retorna h:m:milisegundos formatado)
def formata_tempo_execucao (dttInicio, dttfim):
    strTempo = dttfim - dttInicio
    str_tempo_execucao_formatado = "{:02d}:{:02d}.{:06d}".format(
    strTempo.seconds // 60,  # Minutos
    strTempo.seconds % 60,  # Segundos
    strTempo.microseconds  # Microsegundos
    )
    return str_tempo_execucao_formatado

def formata_data(dttParametro):
  return dttParametro.strftime("%d/%m/%Y - %H:%M:%S.%f")

def formata_numero(numero):
    return locale.format_string("%d", numero, grouping=True)

# Cria um array do tamanho intElementosArray, valores inteiros entre intMin e intMax)
def montar_array (intElementosArray,intMin, intMax):
  x = 0
  array = []
  while x < intTamArray:
    intElementosArray = random.randint(intMin,intMax)
    array.append (intElementosArray)
    x += 1
  return (array)

def ler_inteiro (strMensagem):
  while True:
    try:      # Se nenhuma exceção ocorrer, a cláusula except é ignorada e a execução da instrução try é finalizada
      tamanho = int(input(strMensagem))
      break  # Se a entrada for válida, sai do loop e finaliza o programa
    except ValueError:
      print("Erro: Por favor, digite um número inteiro valido.")
  return tamanho


def carregar_array():
    arrMeuArray = []
    while True:
        entrada = input("Digite um número inteiro para o array (-1 para sair): ")
        try:
            numero = int(entrada)
        except ValueError:
            print("Por favor, digite um número inteiro válido.")
            continue
        if numero == -1:
            break
        arrMeuArray.append(numero)
        print (f"O array atual tem {str(len(arrMeuArray))}. Seu conteúdo é \n")
        print (arrMeuArray)
    return arrMeuArray

def marcar_inicio (strMensagem):
  dttInicio = datetime.now(con_fuso_horario)
  dttInicioFormatado = formata_data(dttInicio)
  print(f"Iniciando {strMensagem} as : " + str(dttInicioFormatado))
  return dttInicio

def marcar_fim (strMensagem):
  dttFim = datetime.now(con_fuso_horario)
  dttFimFormatado = formata_data (dttFim)
  print(f"Finalizando {strMensagem} as : " + str(dttFimFormatado))
  return dttFim

"""# Aula 01

**Exemplo 01 - O(1)**
"""

arrMeuArray = [0,1,4,6,7,1,7,8,5,4,'']

# Data impressa não formatada e com timezone errado. PROPOSITAL PARA DEMONSTRAR ERROS.

print("Data impressa não formatada e com timezone errado. PROPOSITAL PARA DEMONSTRAR ERROS.\n")

dttInicio = datetime.now()
print("Iniciando a adição de um elemento ao array as : " + str(dttInicio))

intElementoArray = random.randint(0,10000000)
arrMeuArray.append (intElementoArray)

dttFim = datetime.now()
print("Finalizando a adição de um elemento ao array as : " + str(dttFim))
print("Tempo de execucao foi de: : " + (str(dttFim - dttInicio)))

print (f"O array é: {arrMeuArray}")

